package controllers;

//DISEÑO MVC
//VISTA ES LO QUE VE EL USUARIO
//CONTROLADOR ES LA LOGICA DEL USUARIO, LOS METODOS (AQUI VAN LOS ALGORITMOS)
//MODELO --> CLASES QUE VAN A ESTAR EN CONTACTO DIRECTO CON LA BD

public class UserController {

}
